export const cardData = [
  {
    id: 1,
    reviewerName: "James T.",
    reviewDate: "5 months ago",
    location: "Ikate, Lagos",
    rating: 3,
    likes: 24,
    dislikes: 2,
    comments: 125,
    category: "traffic",
    review:
      "There is no stable electricity. The roads are fairly good and there is a sense of community. The drainage system is poor and most residents litter their surroundings. There are lots stores and supermarkets.",
  },
  {
    id: 2,
    reviewerName: "John D.",
    reviewDate: "3 months ago",
    location: "Victoria Island, Lagos",
    rating: 4,
    likes: 32,
    dislikes: 1,
    comments: 92,
    category: "road",
    review:
      "Great neighborhood with excellent amenities. Good schools and hospitals nearby. The only downside is occasional traffic congestion.",
  },
  {
    id: 3,
    reviewerName: "Jane Smith",
    reviewDate: "1 year ago",
    location: "Marina, Lagos",
    rating: 5,
    likes: 50,
    dislikes: 0,
    comments: 150,
    category: "water",
    review:
      "The water supply in this area is excellent. We rarely face any water shortages, and the quality of water is top-notch.",
  },
  {
    id: 4,
    reviewerName: "Alex Johnson",
    reviewDate: "6 months ago",
    location: "Yaba, Lagos",
    rating: 2,
    likes: 10,
    dislikes: 5,
    comments: 75,
    category: "power",
    review:
      "The electricity supply is inconsistent in this area. We frequently experience power outages, which can be frustrating.",
  },
  {
    id: 5,
    reviewerName: "Emily Wilson",
    reviewDate: "4 months ago",
    location: "Ikeja, Lagos",
    rating: 4,
    likes: 42,
    dislikes: 3,
    comments: 110,
    category: "traffic",
    review:
      "Traffic congestion is a common issue in this area, especially during rush hours. However, the public transportation system is efficient.",
  },
  {
    id: 6,
    reviewerName: "Michael Brown",
    reviewDate: "2 years ago",
    location: "Surulere, Lagos",
    rating: 3,
    likes: 20,
    dislikes: 2,
    comments: 80,
    category: "road",
    review:
      "The condition of roads in this area varies. Some roads are well-maintained, while others have potholes and require repair.",
  },
  {
    id: 7,
    reviewerName: "Sarah Lee",
    reviewDate: "8 months ago",
    location: "Lekki, Lagos",
    rating: 5,
    likes: 60,
    dislikes: 0,
    comments: 200,
    category: "water",
    review:
      "The water quality in this area is exceptional. We've never faced any issues with water supply, and it's safe for drinking.",
  },
  {
    id: 8,
    reviewerName: "David Clark",
    reviewDate: "7 months ago",
    location: "Ajah, Lagos",
    rating: 4,
    likes: 35,
    dislikes: 1,
    comments: 150,
    category: "power",
    review:
      "Overall, the electricity supply is reliable in this area. We rarely experience power outages, and the voltage is stable.",
  },
  {
    id: 9,
    reviewerName: "Olivia Moore",
    reviewDate: "10 months ago",
    location: "Ikorodu, Lagos",
    rating: 2,
    likes: 15,
    dislikes: 6,
    comments: 90,
    category: "road",
    review:
      "The roads in this area are in poor condition. They are riddled with potholes, and there's a lack of proper maintenance.",
  },
  {
    id: 10,
    reviewerName: "Daniel White",
    reviewDate: "9 months ago",
    location: "Agege, Lagos",
    rating: 3,
    likes: 25,
    dislikes: 3,
    comments: 120,
    category: "water",
    review:
      "The water supply is decent in this area. However, there are occasional disruptions, and the water pressure can be low at times.",
  },
];
